version: 0.2

phases:
  build:
    commands:
      - ./gradlew assembleDebug
artifacts:
  files:
    - '**/*TeamCode-debug.apk'
  base-directory: 'TeamCode/build/outputs/apk/debug/*'
  discard-paths: yes
    